version: '3'

services:

  mongo:
    image: mongo:bionic
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo-root
      MONGO_INITDB_DATABASE: smarthome
    volumes:
      - ./data/mongo:/data/db

  mysql:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: smarthome-root
      MYSQL_USER: smarthome-server
      MYSQL_PASSWORD: smarthome
      MYSQL_DATABASE: smarthomedb
    volumes:
      - ./data/mysql:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "3181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "10092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_BROKER_ID: 500
      KAFKA_offsets_topic_replication_factor: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/500:/kafka
    depends_on:
      - zookeeper

